<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>PDF Cetakan</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        h1 {
            color: #2E8B57;
        }
    </style>
</head>

<body>
    <h1>Ini adalah PDF yang dihasilkan dari View</h1>
    <p>Generated by dompdf using CodeIgniter.</p>
    <table border="1" cellpadding="5" cellspacing="0">
        <thead>
            <tr>
                <th>No</th>
                <th>Nama</th>
                <th>Alamat</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>John Doe</td>
                <td>Jl. Example No. 1</td>
            </tr>
            <tr>
                <td>2</td>
                <td>Jane Doe</td>
                <td>Jl. Example No. 2</td>
            </tr>
        </tbody>
    </table>
</body>

</html>